export enum StoresList {
  APPLICATION = 'application',
  ADMIN = 'admin',
  USER = 'user',
  ACTORS = 'actors',
  HIGHLIGHTS = 'highlights',
  PROJECTS = 'projects',
  ATLAS = 'atlas',
  QGIS_MAP = 'qgisMap',
  RESOURCES = 'resources',
  THEMATICS = 'thematics',
  HOME = 'home',
  MY_MAP = 'myMap',
  ADMINISTRATIVE_BOUNDARIES = 'administrativeBoundaries',
  COMMENT = 'comment',
  DIVERCITY_SPACES = 'divercitySpaces',
  DIVERCITY_BOOKINGS = 'divercityBookings',
  DIVERCITY_BLOCKED_PERIODS = 'divercityBlockedPeriods',
  DIVERCITY_MY_BOOKINGS = 'divercityMyBookings',
  DIVERCITY_HIGHLIGHTS = 'divercityHighlights',
  KPIS = 'kpis',
  STATS = 'stats'
}
